# Generated by Django 5.2.7 on 2025-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CASHIER', 'Кассир'), ('OPERATOR', 'Оператор'), ('ADMIN', 'Админ'), ('CLIENT', 'КЛИЕНТ'), ('EMPLOYEE', 'Сотрудник')], default='CLIENT', max_length=10),
        ),
    ]
