# Generated by Django 5.2.7 on 2025-11-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
    ]
