# Generated by Django 5.2.7 on 2025-11-06 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionskating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionskating',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершен'), ('EXPIRED', 'Истек')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionskating',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessionskating',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionskating',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
