# Generated by Django 5.2.7 on 2025-11-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_add_department_position_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='skating_status',
            field=models.CharField(choices=[('WAITING', 'Ожидает'), ('IN_PROGRESS', 'В процессе'), ('TIME_EXPIRED', 'Время вышло'), ('FINISHED', 'Завершен')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionskating',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидает'), ('IN_PROGRESS', 'В процессе'), ('TIME_EXPIRED', 'Время вышло'), ('FINISHED', 'Завершен')], default='WAITING', max_length=20),
        ),
    ]
