# Generated by Django 5.2.7 on 2025-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_fiscal_error_payment_fiscal_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fiscal_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
