# Generated by Django 5.2.7 on 2025-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_fiscal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fiscal_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
